name: CI

on:
  push:
    branches:
      - 'main'

env:
  DESTDIR: ./bin
  GO_VERSION: 1.22.4

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t docker.io/frankmd/dev-ops-nlw:${{ steps.generate_sha.outputs.sha }} .

      - name: Push Docker image
        run: |
          docker push docker.io/frankmd/dev-ops-nlw:${{ steps.generate_sha.outputs.sha }}
          docker tag docker.io/frankmd/dev-ops-nlw:${{ steps.generate_sha.outputs.sha }} docker.io/frankmd/dev-ops-nlw:latest
          docker push docker.io/frankmd/dev-ops-nlw:latest

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install deps (ubuntu)
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install -y dbus-x11 gnome-keyring libsecret-1-dev pass

      - name: Test
        run: |
          make test COVERAGEDIR=${{ env.DESTDIR }}
        shell: bash

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ${{ env.DESTDIR }}/coverage.txt
